### PR TITLE
updated tox

### PR DESCRIPTION
**Pull request by rollbee10**
updated tox

### CODE REVIEW

**Comment by isaacm** [comment]
Please rebase.

**Review by isaacm — APPROVED** [review]
Test environment invokes all tox versions, but some unit tests are still failing.

**Comment by tonytan4ever** [comment]
How come travis is still failing though ?

**Review by tonytan4ever — APPROVED** [review]
Need to fix failing travis gate:
https://travis-ci.com/tonytan4ever/python-marketsearch-api-sdk/jobs/283515983

**Comment by isaacm** [comment]
The unit tests need to be fixed. Travis/Tox parts work as expected.

**Pull request merged**
